### ISSUE TITLE
Asset library: invalid commit hash

### ISSUE THREAD

**Issue by akien-mga** [Timofffee/FlappyGodot#1]
Hi,

You gave an invalid commit hash ("Download Commit") on the Godot Asset Library: https://godotengine.org/asset-library/asset/edit/198

You used `v0.1` but you have no tag with this name, so it won't work. You should either tag version `v0.1` so that it works, or use a commit hash instead, e.g. `a6bf1285e0fb9ea1b4abef75e7234360d92164d4`.
Note that you can edit your submission directly from the interface.

**Comment by akien-mga** [comment]
Ping.

**Comment by akien-mga** [comment]
Had to reject the edit since it would not work: https://godotengine.org/asset-library/asset/edit/198

But please feel free to submit it again with a proper commit hash as explained above :)

**Comment by Timofffee** [comment]
Oh, sorry. I haven't been to Github this year. I'll fix that.
